---
title: "p8105_hw3_jy3269"
author: "Jingyi Yao"
date: "`r Sys.Date()`"
output: github_document
---

```{r,warning=FALSE, message=FALSE}
library(tidyverse)
library(p8105.datasets)
```

## Problem 2

### 1. import csv file
```{r}
data_1 <- read_csv("./data/accel_data.csv")
data_1

```

### 2. clean and wrangle data

```{r}
acc_1 <- data_1 %>% 
  janitor::clean_names() %>% 
  mutate(
    week = as.integer(week),
    day_id = as.integer(day_id),
    weekday_vs_weekend = if_else(day == "Saturday" | day == "Sunday","weekend","weekday") # new variable indicate whether the day is weekend or weekday
  ) %>% 
  pivot_longer(                          # switch the data set from wider to longer
    activity_1:activity_1440,
    names_to = "minute",                 # activity_number in previous column names indicate the minute       
    names_prefix = "activity_",          # remove the activity_ prefix and preserve the number
    values_to = "activity_counts") %>%   # store the observed data in a new column names activity_counts
  mutate(minute = as.integer(minute))    # change the data class

acc_1
```

```{r}
acc_2 <- data_1 %>% 
  janitor::clean_names() %>% 
  mutate(
    week = as.integer(week),
    day_id = as.integer(day_id),
    weekday_vs_weekend = if_else(day == "Saturday" | day == "Sunday","weekend","weekday") # new variable indicate whether the day is weekend or weekday
  ) %>% 
  select(week,day_id,day,weekday_vs_weekend,everything())

acc_2

```



### 3. total activity each day
```{r}
acc_2 %>% 
  group_by(day_id) %>% 
  mutate(total_activity = sum(activity_1:activity_1440)) %>%     # add a column to store the daily sum
  select(week,day_id,day,weekday_vs_weekend,total_activity,everything()) # show the new column at the front

```


```{r}
acc_1 %>% 
  group_by(day_id) %>% 
  mutate(total_activity = sum(activity_counts))     # add a column to store the daily sum

```




### 4. make a table

```{r}
acc_2 %>% 
  group_by(day_id) %>% 
  summarize(total_activity = sum(activity_1:activity_1440)) %>% 
  knitr::kable()    # make an r table

```


```{r}
acc_1 %>% 
  group_by(day_id) %>% 
  summarize(total_activity = sum(activity_counts)) %>% 
  knitr::kable()    # make an r table

```



### 5. plot daily activity
```{r}
acc_1 %>%  
  group_by(day_id) %>%
  ggplot(aes(x = minute,y = activity_counts,color = day)) +
  geom_point() + geom
  
```




## Problem 3

### 1. load `ny_noaa` data set
```{r}
data("ny_noaa")
head(ny_noaa)
```


### 2. clean  data
```{r}
ny_noaa <- ny_noaa %>% 
  separate(date,into = c("year","month","day"),sep="-") %>% 
  mutate(
    year = as.numeric(year),
    month = as.integer(month),
    day = as.numeric(day),
    tmax = as.numeric(tmax)
  )

ny_noaa
  
```


### 3. snowfall
```{r}
ny_noaa %>% 
  group_by(snow) %>% 
  summarise(counts = n()) %>%  # count the occurrence of each observed snowfall data
  arrange(desc(counts))        # arrange the counts in descending order to find the most frequent ones

```

### 4. plot mean tmax
```{r}
ny_noaa %>% 
  filter(month == c(7)) %>% 
  group_by(id) %>% 
  mutate(mean_tmax = mean(tmax,na.rm = TRUE)) %>% 
  ggplot(aes(y = mean_tmax,fill = year))+
  geom_histogram()

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```























